events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name api.airtel.tv;

        location /v1/user/config {
            default_type application/json;
            return 200 '{"status": "ok", "service": "api.airtel.tv", "message": "Dummy user config response"}';
        }
    }

    server {
        listen 80;
        server_name epg.airtel.tv;

        location /v1/user/epg {
            default_type application/json;
            return 200 '{"status": "ok", "service": "epg.airtel.tv", "message": "Dummy EPG response"}';
        }
    }
}