name: projects/prj-wynk-prd-iptv-svc-01/locations/global/edgeCacheServices/iptv-live-play-auth
updateTime: '2025-02-28T19:32:23.092857161Z'
description: iptv-live-play-auth
labels:
  product: dth
  purpose: mediacdn
  role: iptv
  environment: production
  pod: iptv
requireTls: true
edgeSslCertificates:
  - projects/699779264026/locations/global/certificates/iptv-live-play
  - projects/699779264026/locations/global/certificates/iptv-live-play-auth
ipv4Addresses:
  - 34.126.227.193
ipv6Addresses:
  - '2600:1900:8010:16c5::'
routing:
  hostRules:
    - description: iptv-live-playauth.streamready.in
      hosts:
        - iptv-live-playauth.streamready.in
        - iptv-live-play1.streamready.in
      pathMatcher: path-matcher-0
  pathMatchers:
    - name: path-matcher-0
      routeRules:
        - priority: '10'
          description: vdashd *.mpd
          matchRules:
            - ignoreCase: true
              pathTemplateMatch: /live/*/*/vdashd/*.mpd
          origin: projects/699779264026/locations/global/edgeCacheOrigins/nea-live-1-ssl
          headerAction:
            responseHeadersToAdd:
              - headerName: x-cdn-cache-status
                headerValue: '{cdn_cache_status}'
          routeAction:
            cdnPolicy:
              cacheMode: FORCE_CACHE_ALL
              clientTtl: 2s
              defaultTtl: 2s
              cacheKeyPolicy:
                excludeQueryString: true
              negativeCaching: true
              negativeCachingPolicy:
                '501': 3s
                '502': 3s
                '404': 2s
                '405': 30s
                '500': 3s
              signedRequestMode: REQUIRE_SIGNATURES
              signedRequestKeyset: projects/prj-wynk-prd-iptv-svc-01/locations/global/edgeCacheKeysets/iptv-prod-media-cdn-keys
        - priority: '30'
          description: dashd *.mpd
          matchRules:
            - ignoreCase: true
              pathTemplateMatch: /live/*/*/dashd/*.mpd
          origin: projects/699779264026/locations/global/edgeCacheOrigins/nea-live-1-ssl
          headerAction:
            responseHeadersToAdd:
              - headerName: x-cdn-cache-status
                headerValue: '{cdn_cache_status}'
          routeAction:
            cdnPolicy:
              cacheMode: FORCE_CACHE_ALL
              clientTtl: 2s
              defaultTtl: 2s
              cacheKeyPolicy:
                excludeQueryString: true
              negativeCaching: true
              negativeCachingPolicy:
                '404': 2s
                '405': 30s
                '500': 3s
                '501': 3s
                '502': 3s
              signedRequestMode: REQUIRE_SIGNATURES
              signedRequestKeyset: projects/prj-wynk-prd-iptv-svc-01/locations/global/edgeCacheKeysets/iptv-prod-media-cdn-keys
        - priority: '50'
          description: dashd *.mp4
          matchRules:
            - ignoreCase: true
              pathTemplateMatch: /live/*/*/dashd/*.mp4
          origin: projects/699779264026/locations/global/edgeCacheOrigins/nea-live-1-ssl
          headerAction:
            responseHeadersToAdd:
              - headerName: x-cdn-cache-status
                headerValue: '{cdn_cache_status}'
          routeAction:
            cdnPolicy:
              cacheMode: FORCE_CACHE_ALL
              clientTtl: 1800s
              defaultTtl: 1800s
              cacheKeyPolicy:
                excludeQueryString: true
              negativeCaching: true
              negativeCachingPolicy:
                '500': 3s
                '501': 3s
                '502': 3s
                '404': 2s
                '405': 30s
              signedRequestMode: REQUIRE_SIGNATURES
              signedRequestKeyset: projects/prj-wynk-prd-iptv-svc-01/locations/global/edgeCacheKeysets/iptv-prod-media-cdn-keys
        - priority: '70'
          description: vdashd *.mp4
          matchRules:
            - ignoreCase: true
              pathTemplateMatch: /live/*/*/vdashd/*.mp4
          origin: projects/699779264026/locations/global/edgeCacheOrigins/nea-live-1-ssl
          headerAction:
            responseHeadersToAdd:
              - headerName: x-cdn-cache-status
                headerValue: '{cdn_cache_status}'
          routeAction:
            cdnPolicy:
              cacheMode: FORCE_CACHE_ALL
              clientTtl: 1800s
              defaultTtl: 1800s
              cacheKeyPolicy:
                excludeQueryString: true
              negativeCaching: true
              negativeCachingPolicy:
                '405': 30s
                '500': 3s
                '501': 3s
                '502': 3s
                '404': 2s
              signedRequestMode: REQUIRE_SIGNATURES
              signedRequestKeyset: projects/prj-wynk-prd-iptv-svc-01/locations/global/edgeCacheKeysets/iptv-prod-media-cdn-keys
        - priority: '11'
          description: vdashhd/*.mpd
          matchRules:
            - pathTemplateMatch: /live/*/*/vdashhd/*.mpd
          origin: projects/699779264026/locations/global/edgeCacheOrigins/nea-live-1-ssl
          headerAction:
            responseHeadersToAdd:
              - headerName: x-cdn-cache-status
                headerValue: '{cdn_cache_status}'
          routeAction:
            cdnPolicy:
              cacheMode: FORCE_CACHE_ALL
              clientTtl: 2s
              defaultTtl: 2s
              cacheKeyPolicy:
                excludeQueryString: true
              negativeCaching: true
              negativeCachingPolicy:
                '404': 2s
                '405': 30s
                '500': 3s
                '501': 3s
                '502': 3s
              signedRequestMode: REQUIRE_SIGNATURES
              signedRequestKeyset: projects/prj-wynk-prd-iptv-svc-01/locations/global/edgeCacheKeysets/iptv-prod-media-cdn-keys
        - priority: '31'
          description: dashhd/*.mpd
          matchRules:
            - pathTemplateMatch: /live/*/*/dashhd/*.mpd
          origin: projects/699779264026/locations/global/edgeCacheOrigins/nea-live-1-ssl
          headerAction:
            responseHeadersToAdd:
              - headerName: x-cdn-cache-status
                headerValue: '{cdn_cache_status}'
          routeAction:
            cdnPolicy:
              cacheMode: FORCE_CACHE_ALL
              clientTtl: 2s
              defaultTtl: 2s
              cacheKeyPolicy:
                excludeQueryString: true
              negativeCaching: true
              negativeCachingPolicy:
                '404': 2s
                '405': 30s
                '500': 3s
                '501': 3s
                '502': 3s
              signedRequestMode: REQUIRE_SIGNATURES
              signedRequestKeyset: projects/prj-wynk-prd-iptv-svc-01/locations/global/edgeCacheKeysets/iptv-prod-media-cdn-keys
        - priority: '51'
          description: vdashhd/*.mp4
          matchRules:
            - pathTemplateMatch: /live/*/*/vdashhd/*.mp4
          origin: projects/699779264026/locations/global/edgeCacheOrigins/nea-live-1-ssl
          headerAction:
            responseHeadersToAdd:
              - headerName: x-cdn-cache-status
                headerValue: '{cdn_cache_status}'
          routeAction:
            cdnPolicy:
              cacheMode: FORCE_CACHE_ALL
              clientTtl: 1800s
              defaultTtl: 1800s
              cacheKeyPolicy:
                excludeQueryString: true
              negativeCaching: true
              negativeCachingPolicy:
                '500': 3s
                '501': 3s
                '502': 3s
                '404': 2s
                '405': 30s
              signedRequestMode: REQUIRE_SIGNATURES
              signedRequestKeyset: projects/prj-wynk-prd-iptv-svc-01/locations/global/edgeCacheKeysets/iptv-prod-media-cdn-keys
        - priority: '71'
          description: dashhd/*.mp4
          matchRules:
            - pathTemplateMatch: /live/*/*/dashhd/*.mp4
          origin: projects/699779264026/locations/global/edgeCacheOrigins/nea-live-1-ssl
          headerAction:
            responseHeadersToAdd:
              - headerName: x-cdn-cache-status
                headerValue: '{cdn_cache_status}'
          routeAction:
            cdnPolicy:
              cacheMode: FORCE_CACHE_ALL
              clientTtl: 1800s
              defaultTtl: 1800s
              cacheKeyPolicy:
                excludeQueryString: true
              negativeCaching: true
              negativeCachingPolicy:
                '500': 3s
                '501': 3s
                '502': 3s
                '404': 2s
                '405': 30s
              signedRequestMode: REQUIRE_SIGNATURES
              signedRequestKeyset: projects/prj-wynk-prd-iptv-svc-01/locations/global/edgeCacheKeysets/iptv-prod-media-cdn-keys
        - priority: '12'
          description: /live/*/*/vdashshd/*.mpd
          matchRules:
            - pathTemplateMatch: /live/*/*/vdashshd/*.mpd
          origin: projects/699779264026/locations/global/edgeCacheOrigins/nea-live-1-ssl
          headerAction:
            responseHeadersToAdd:
              - headerName: x-cdn-cache-status
                headerValue: '{cdn_cache_status}'
          routeAction:
            cdnPolicy:
              cacheMode: FORCE_CACHE_ALL
              clientTtl: 2s
              defaultTtl: 2s
              cacheKeyPolicy:
                excludeQueryString: true
              negativeCaching: true
              negativeCachingPolicy:
                '404': 2s
                '405': 30s
                '500': 3s
                '501': 3s
                '502': 3s
              signedRequestMode: REQUIRE_SIGNATURES
              signedRequestKeyset: projects/prj-wynk-prd-iptv-svc-01/locations/global/edgeCacheKeysets/iptv-prod-media-cdn-keys
        - priority: '32'
          description: /live/*/*/dashshd/*.mpd
          matchRules:
            - pathTemplateMatch: /live/*/*/dashshd/*.mpd
          origin: projects/699779264026/locations/global/edgeCacheOrigins/nea-live-1-ssl
          headerAction:
            responseHeadersToAdd:
              - headerName: x-cdn-cache-status
                headerValue: '{cdn_cache_status}'
          routeAction:
            cdnPolicy:
              cacheMode: FORCE_CACHE_ALL
              clientTtl: 2s
              defaultTtl: 2s
              cacheKeyPolicy:
                excludeQueryString: true
              negativeCaching: true
              negativeCachingPolicy:
                '500': 3s
                '501': 3s
                '502': 3s
                '404': 2s
                '405': 30s
              signedRequestMode: REQUIRE_SIGNATURES
              signedRequestKeyset: projects/prj-wynk-prd-iptv-svc-01/locations/global/edgeCacheKeysets/iptv-prod-media-cdn-keys
        - priority: '52'
          description: /live/*/*/vdashshd/*.mp4
          matchRules:
            - pathTemplateMatch: /live/*/*/vdashshd/*.mp4
          origin: projects/699779264026/locations/global/edgeCacheOrigins/nea-live-1-ssl
          headerAction:
            responseHeadersToAdd:
              - headerName: x-cdn-cache-status
                headerValue: '{cdn_cache_status}'
          routeAction:
            cdnPolicy:
              cacheMode: FORCE_CACHE_ALL
              clientTtl: 1800s
              defaultTtl: 1800s
              cacheKeyPolicy:
                excludeQueryString: true
              negativeCaching: true
              negativeCachingPolicy:
                '502': 3s
                '404': 2s
                '405': 30s
                '500': 3s
                '501': 3s
              signedRequestMode: REQUIRE_SIGNATURES
              signedRequestKeyset: projects/prj-wynk-prd-iptv-svc-01/locations/global/edgeCacheKeysets/iptv-prod-media-cdn-keys
        - priority: '72'
          description: /live/*/*/dashshd/*.mp4
          matchRules:
            - pathTemplateMatch: /live/*/*/dashshd/*.mp4
          origin: projects/699779264026/locations/global/edgeCacheOrigins/nea-live-1-ssl
          headerAction:
            responseHeadersToAdd:
              - headerName: x-cdn-cache-status
                headerValue: '{cdn_cache_status}'
          routeAction:
            cdnPolicy:
              cacheMode: FORCE_CACHE_ALL
              clientTtl: 1800s
              defaultTtl: 1800s
              cacheKeyPolicy:
                excludeQueryString: true
              negativeCaching: true
              negativeCachingPolicy:
                '501': 3s
                '502': 3s
                '404': 2s
                '405': 30s
                '500': 3s
              signedRequestMode: REQUIRE_SIGNATURES
              signedRequestKeyset: projects/prj-wynk-prd-iptv-svc-01/locations/global/edgeCacheKeysets/iptv-prod-media-cdn-keys
logConfig:
  enable: true
  sampleRate: 1.0
edgeSecurityPolicy: projects/prj-wynk-prd-iptv-svc-01/global/securityPolicies/cmn-mcdn-esp-loc-india-allow-only-01
createTime: '2024-10-29T04:17:42.671084802Z'