package in.wynk.secret.manager.json;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;

public class JsonExtractor {
    public static String getProgramJson(String jsonContent, String channelId, String programId) {
        try {
            ObjectMapper objectMapper = new ObjectMapper();
            JsonNode rootNode = objectMapper.readTree(jsonContent);
            JsonNode channels = rootNode.path("Schedule").path("channel");

            for (JsonNode channel : channels) {
                if (channel.path("channelid").asText().equals(channelId)) {
                    JsonNode programs = channel.path("programme");
                    for (JsonNode program : programs) {
                        if (program.path("programmeid").asText().equals(programId)) {
                            return objectMapper.writeValueAsString(program);
                        }
                    }
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null; // Return null if not found
    }

    public static void main(String[] args) {
        String jsonContent = """
            {
              "Schedule": {
                "channel": [
                  {
                    "-id": "&Pictures",
                    "channelid": "&Pictures",
                    "channellogourl": "",
                    "genre": "Movies",
                    "channeldisplayname": "&Pictures",
                    "lcn": "211",
                    "price": "10",
                    "programme": [
                      {
                        "programmeid": "333450",
                        "title": "Love Breakups Zindagi",
                        "start": "2024-09-09T19:24:00",
                        "stop": "2024-09-09T21:52:00",
                        "desc": "Despite being in committed relationships, Jai and Naina fall in love with each other and find their lives changing.",
                        "programmeurl": "https://d2sqx12cok5m5h.cloudfront.net/PICTURES_LoveBreakupsZindagi_333450.jpg",
                        "channelid": "&Pictures",
                        "date": "20240910",
                        "episode-num": "",
                        "sub-title": "",
                        "genre": "Comedy",
                        "subgenre": "Drama",
                        "languagename": "Hindi",
                        "isoriginal": "False",
                        "duration": "148",
                        "seasonid": null,
                        "seasonname": null,
                        "rating": "U/A",
                        "country_of_origin": "India",
                        "awards": "",
                        "productionhouse": "Born Free Entertainment",
                        "release_date": "2011",
                        "cast": "Zayed Khan, Dia Mirza, Cyrus Sahukar, Shabana Azmi, Boman Irani",
                        "crew": "Director: Sahil Sangha; Producer: Zayed Khan; Writer: Sanyukta Shaikh Chawla, Sahil Sangha"
                      },
                      {
                        "programmeid": "342728",
                        "title": "Tamasha",
                        "start": "2024-09-09T21:52:00",
                        "stop": "2024-09-10T00:00:00",
                        "desc": "A guy loses himself trying to fit in; Tamasha explores his journey back to authenticity.",
                        "programmeurl": "https://d2sqx12cok5m5h.cloudfront.net/AndPicture_Tamasha_342728.jpg",
                        "channelid": "&Pictures",
                        "date": "20240910",
                        "episode-num": "",
                        "sub-title": "",
                        "genre": "Romance",
                        "subgenre": "Comedy",
                        "languagename": "Hindi",
                        "isoriginal": "False",
                        "duration": "128",
                        "seasonid": null,
                        "seasonname": null,
                        "rating": "U/A",
                        "country_of_origin": "India",
                        "awards": "",
                        "productionhouse": "Nadiadwala Grandson Entertainment",
                        "release_date": "2015",
                        "cast": "Ranbir Kapoor, Deepika Padukone, Javed Sheikh, Nikhil Bhagat",
                        "crew": "Director: Imtiaz Ali; Producer: Sajid Nadiadwala; Writer: Imtiaz Ali"
                      },
                      {
                        "programmeid": "62746",
                        "title": "Filler",
                        "start": "2024-09-10T00:00:00",
                        "stop": "2024-09-10T00:07:00",
                        "desc": "Watch promos, music, and fillers back to back from the movies or shows.",
                        "programmeurl": "https://d2sqx12cok5m5h.cloudfront.net/PICTURES_Filler_62746.jpg",
                        "channelid": "&Pictures",
                        "date": "20240910",
                        "episode-num": "",
                        "sub-title": "",
                        "genre": "Other",
                        "subgenre": "",
                        "languagename": "Hindi",
                        "isoriginal": "False",
                        "duration": "7",
                        "seasonid": null,
                        "seasonname": null,
                        "rating": "U",
                        "country_of_origin": "",
                        "awards": "",
                        "productionhouse": "",
                        "release_date": "0",
                        "cast": "",
                        "crew": ""
                      },
                      {
                        "programmeid": "489665",
                        "title": "Great Grand Masti",
                        "start": "2024-09-17T05:36:00",
                        "stop": "2024-09-17T07:44:00",
                        "desc": "Three friends travel to a small town where they meet Ragini, a beautiful woman. However, they soon realise that she has brought nothing but trouble in their lives.",
                        "programmeurl": "https://d2sqx12cok5m5h.cloudfront.net/PICTURES_GreatGrandMasti_489665.jpg",
                        "channelid": "&Pictures",
                        "date": "20240917",
                        "episode-num": "",
                        "sub-title": "",
                        "genre": "Comedy",
                        "subgenre": "Drama",
                        "languagename": "Hindi",
                        "isoriginal": "False",
                        "duration": "128",
                        "seasonid": null,
                        "seasonname": null,
                        "rating": "A",
                        "country_of_origin": "India",
                        "awards": "",
                        "productionhouse": "Balaji Motion Pictures, Maruti International, Sri Adhikari Brothers",
                        "release_date": "2016",
                        "cast": "Urvashi Rautela, Riteish Deshmukh, Vivek Oberoi, Aftab Shivdasani",
                        "crew": "Director: Indra Kumar; Producer: Sameer Nair, Aman Gill, Ashok Thakeria, Markand Adhikari, Anand Pandit; Writer: Tushar Hiranandani"
                      },
                      {
                        "programmeid": "83685",
                        "title": "Maine Pyar Kiya",
                        "start": "2024-09-17T07:44:00",
                        "stop": "2024-09-17T11:44:00",
                        "desc": "Prem and Suman fall in love only to be torn apart by family clashes. Will Prem prove himself worthy of Suman's love?",
                        "programmeurl": "https://d2sqx12cok5m5h.cloudfront.net/AndPicture_MainePyarKiya_83685.jpg",
                        "channelid": "&Pictures",
                        "date": "20240917",
                        "episode-num": "",
                        "sub-title": "",
                        "genre": "Romance",
                        "subgenre": "Family",
                        "languagename": "Hindi",
                        "isoriginal": "False",
                        "duration": "240",
                        "seasonid": null,
                        "seasonname": null,
                        "rating": "U",
                        "country_of_origin": "India",
                        "awards": "Filmfare Awards:Best Film: Tarachand Barjatya Best Music DirectorBest Lyricist: Asad Bhopali Best Playback Singer: Balasubramaniam S.P. ",
                        "productionhouse": "Rajshri Productions",
                        "release_date": "1989",
                        "cast": "Salman Khan, Bhagyashree, Alok Nath, Rajeev Verma",
                        "crew": "Director: Sooraj R. Barjatya; Producer: Tarachand Barjatya; Writer: Sooraj Barjatya"
                      },
                      {
                        "programmeid": "247344",
                        "title": "Lingaa",
                        "start": "2024-09-17T11:44:00",
                        "stop": "2024-09-17T14:30:00",
                        "desc": "Lingaa transforms into a hero, saving the dam his grandfather built.",
                        "programmeurl": "https://d2sqx12cok5m5h.cloudfront.net/AndPicture_Lingaa_247344.jpg",
                        "channelid": "&Pictures",
                        "date": "20240917",
                        "episode-num": "",
                        "sub-title": "",
                        "genre": "Action",
                        "subgenre": "",
                        "languagename": "Hindi",
                        "isoriginal": "False",
                        "duration": "166",
                        "seasonid": null,
                        "seasonname": null,
                        "rating": "U",
                        "country_of_origin": "India",
                        "awards": "",
                        "productionhouse": "Rockline Entertainments",
                        "release_date": "2014",
                        "cast": "Rajnikanth, Anushka Shetty, Sonakshi Sinha, Santhanam",
                        "crew": "Director: K. S. Ravikumar; Producer: Rockline Venkatesh; Writer: Pon Kumaran, K.S. Ravikumar"
                      },
                      {
                        "programmeid": "342519",
                        "title": "Real Tevar",
                        "start": "2024-09-17T14:30:00",
                        "stop": "2024-09-17T17:19:00",
                        "desc": "Story about a rich guy, who believes in doing what his heart says. Though he has everything in life, there is something else he desires to accomplish.",
                        "programmeurl": "https://d2sqx12cok5m5h.cloudfront.net/PICTURES_RealTevar_342519.jpg",
                        "channelid": "&Pictures",
                        "date": "20240917",
                        "episode-num": "",
                        "sub-title": "",
                        "genre": "Action",
                        "subgenre": "",
                        "languagename": "Hindi",
                        "isoriginal": "False",
                        "duration": "169",
                        "seasonid": null,
                        "seasonname": null,
                        "rating": "U/A",
                        "country_of_origin": "India",
                        "awards": "",
                        "productionhouse": "G.Mahesh BabuEntertainment, MythriMovieMakers",
                        "release_date": "2015",
                        "cast": "Aamani, Jagapathi Babu, Mahesh Babu, Shruti Haasan",
                        "crew": "Director: Koratalla Siva; Producer: Naveen Yerneni, Yalamanchili Ravi Shankar, C. V. Mohan; Writer: Koratalla Siva"
                      },
                      {
                        "programmeid": "318212",
                        "title": "Alone",
                        "start": "2024-09-17T17:19:00",
                        "stop": "2024-09-17T20:30:00",
                        "desc": "Two twin sisters who lived by one promise - 'We will always be together. We will never separate'. Later, the ghost of dead haunt the surviving sister.",
                        "programmeurl": "https://d2sqx12cok5m5h.cloudfront.net/PICTURES_Alone_318212.jpg",
                        "channelid": "&Pictures",
                        "date": "20240917",
                        "episode-num": "",
                        "sub-title": "",
                        "genre": "Horror",
                        "subgenre": "Romance",
                        "languagename": "Hindi",
                        "isoriginal": "False",
                        "duration": "191",
                        "seasonid": null,
                        "seasonname": null,
                        "rating": "A",
                        "country_of_origin": "India",
                        "awards": "",
                        "productionhouse": " Panorama Studios",
                        "release_date": "2015",
                        "cast": "Bipasha Basu, Karan Singh Grover, Zakir Hussain",
                        "crew": "Director: Bhushan Patel; Producer: Kumar Mangat, Pathak, Abhishek Pathak, Pradeep Agarwal,Prashant Sharma; Writer: Shiirshak S. Anand, Shantanu Ray Chhibber, Shagufta Rafique"
                      },
                      {
                        "programmeid": "193629",
                        "title": "Movie",
                        "start": "2024-09-17T20:30:00",
                        "stop": "2024-09-18T00:45:00",
                        "desc": "Movie name is yet to be announced by this channel.",
                        "programmeurl": "https://d2sqx12cok5m5h.cloudfront.net/PICTURES_Movie_193629.jpg",
                        "channelid": "&Pictures",
                        "date": "20240918",
                        "episode-num": "",
                        "sub-title": "",
                        "genre": "Movie",
                        "subgenre": "",
                        "languagename": "Hindi",
                        "isoriginal": "False",
                        "duration": "255",
                        "seasonid": null,
                        "seasonname": null,
                        "rating": "U",
                        "country_of_origin": "",
                        "awards": "",
                        "productionhouse": "",
                        "release_date": "",
                        "cast": "Chris Pratt, Anya Taylor-Joy, Charlie Day, Jack Black",
                        "crew": ""
                      },
                      {
                        "programmeid": "193629",
                        "title": "Movie",
                        "start": "2024-09-18T00:45:00",
                        "stop": "2024-09-18T02:31:00",
                        "desc": "Movie name is yet to be announced by this channel.",
                        "programmeurl": "https://d2sqx12cok5m5h.cloudfront.net/PICTURES_Movie_193629.jpg",
                        "channelid": "&Pictures",
                        "date": "20240918",
                        "episode-num": "",
                        "sub-title": "",
                        "genre": "Movie",
                        "subgenre": "",
                        "languagename": "Hindi",
                        "isoriginal": "False",
                        "duration": "106",
                        "seasonid": null,
                        "seasonname": null,
                        "rating": "U",
                        "country_of_origin": "",
                        "awards": "",
                        "productionhouse": "",
                        "release_date": "",
                        "cast": "Chris Pratt, Anya Taylor-Joy, Charlie Day, Jack Black",
                        "crew": ""
                      },
                      {
                        "programmeid": "1481560",
                        "title": "Phone Bhoot",
                        "start": "2024-09-18T02:31:00",
                        "stop": "2024-09-18T05:11:00",
                        "desc": "Inspired by stories from their childhood, two young men create a business around capturing ghosts. However, their endeavour turns dangerous when they must fulfil their promise to a poltergeist.",
                        "programmeurl": "https://d2sqx12cok5m5h.cloudfront.net/PICTURES_PhoneBhoot_1481560.jpg",
                        "channelid": "&Pictures",
                        "date": "20240918",
                        "episode-num": "",
                        "sub-title": "",
                        "genre": "Comedy",
                        "subgenre": "Horror",
                        "languagename": "Hindi",
                        "isoriginal": "False",
                        "duration": "160",
                        "seasonid": null,
                        "seasonname": null,
                        "rating": "U/A",
                        "country_of_origin": "India",
                        "awards": "",
                        "productionhouse": "Excel Entertainment",
                        "release_date": "2022",
                        "cast": "Katrina Kaif, Ishaan Khatter, Siddhant Chaturvedi, Naufal Azmir Khan",
                        "crew": "Director: Gurmmeet Singh; Producer: Ritesh Sidhwani, Farhan Akhtar; Writer: Ravi Shankaran, Jasvinder Singh Bath"
                      },
                      {
                        "programmeid": "327133",
                        "title": "Jigarwala No.1",
                        "start": "2024-09-18T05:11:00",
                        "stop": "2024-09-18T07:56:00",
                        "desc": "Dr Robin comes to India to recover his land from a gangster. He is persuaded by a writer who has a hidden agenda.",
                        "programmeurl": "https://d2sqx12cok5m5h.cloudfront.net/PICTURES_JigarwalaNo1_327133.jpg",
                        "channelid": "&Pictures",
                        "date": "20240918",
                        "episode-num": "",
                        "sub-title": "",
                        "genre": "Action",
                        "subgenre": "",
                        "languagename": "Hindi",
                        "isoriginal": "False",
                        "duration": "165",
                        "seasonid": null,
                        "seasonname": null,
                        "rating": "U/A",
                        "country_of_origin": "India",
                        "awards": "",
                        "productionhouse": "N.T.R. Arts",
                        "release_date": "2015",
                        "cast": "Ravi Teja, Rakul Preet Singh, Brahmanandam, Tanikella Bharani",
                        "crew": "Director: Surender Reddy, Gogu; Producer: Nandamuri Kalyan Ram; Writer: Vakkantham Vamsi, Surender Reddy, Prasad Rishi"
                      },
                      {
                        "programmeid": "83686",
                        "title": "Mr. India",
                        "start": "2024-09-18T07:56:00",
                        "stop": "2024-09-18T11:33:00",
                        "desc": "A poor man takes orphans into his home. After discovering his father's invisibility device, he fights to save his children.",
                        "programmeurl": "https://d2sqx12cok5m5h.cloudfront.net/PICTURES_MrIndia_83686.jpg",
                        "channelid": "&Pictures",
                        "date": "20240918",
                        "episode-num": "",
                        "sub-title": "",
                        "genre": "Action",
                        "subgenre": "SciFi",
                        "languagename": "Hindi",
                        "isoriginal": "False",
                        "duration": "217",
                        "seasonid": null,
                        "seasonname": null,
                        "rating": "U",
                        "country_of_origin": "India",
                        "awards": "",
                        "productionhouse": "Narsimha Enterprises",
                        "release_date": "1987",
                        "cast": "Anil Kapoor, Sridevi Kapoor, Amrish Puri, Satish Kaushik",
                        "crew": "Director: Shekhar Kapur; Producer: Boney Kapoor, Surinder Kapoor; Writer: Javed Akhtar, Salim Khan "
                      },
                      {
                        "programmeid": "907601",
                        "title": "No1 Businessman",
                        "start": "2024-09-18T11:33:00",
                        "stop": "2024-09-18T14:00:00",
                        "desc": "A man visits Mumbai with the aim of ruling the city. He turns into a don and manages to become a businessman. His intentions are not what they seem.",
                        "programmeurl": "https://d2sqx12cok5m5h.cloudfront.net/PICTURES_No1Businessman_907601.jpg",
                        "channelid": "&Pictures",
                        "date": "20240918",
                        "episode-num": "",
                        "sub-title": "",
                        "genre": "Action",
                        "subgenre": "",
                        "languagename": "Hindi",
                        "isoriginal": "False",
                        "duration": "147",
                        "seasonid": null,
                        "seasonname": null,
                        "rating": "UA",
                        "country_of_origin": "",
                        "awards": "",
                        "productionhouse": "",
                        "release_date": "",
                        "cast": "",
                        "crew": ""
                      },
                      {
                        "programmeid": "954233",
                        "title": "Dream Girl",
                        "start": "2024-09-18T14:00:00",
                        "stop": "2024-09-18T16:39:00",
                        "desc": "Karamveer gets a job at a call centre due to his ability to talk in a woman's voice. He garners a big fan following but soon gets in trouble with his overzealous clients.",
                        "programmeurl": "https://d2sqx12cok5m5h.cloudfront.net/PICTURES_DreamGirl_954233.jpg",
                        "channelid": "&Pictures",
                        "date": "20240918",
                        "episode-num": "",
                        "sub-title": "",
                        "genre": "Comedy",
                        "subgenre": "Romance",
                        "languagename": "Hindi",
                        "isoriginal": "False",
                        "duration": "159",
                        "seasonid": null,
                        "seasonname": null,
                        "rating": "U/A",
                        "country_of_origin": "India",
                        "awards": "",
                        "productionhouse": "Balaji Motion Pictures, ALT Entertainment",
                        "release_date": "2019",
                        "cast": "Ayushmann Khurrana, Nushrat Bharucha, Annu Kapoor, Manjot Singh",
                        "crew": "Director: Raaj Shaandilyaa; Producer: Ekta Kapoor, Shobha Kapoor; Writer: Nirmaan D Singh, Raaj Shaandilyaa"
                      },
                      {
                        "programmeid": "1191829",
                        "title": "Radhe",
                        "start": "2024-09-18T16:39:00",
                        "stop": "2024-09-18T20:30:00",
                        "desc": "After taking the dreaded gangster Gani Bhai, ACP Rajveer Shikawat aka Radhe goes on a manhunt to find the wealthiest man of the town secretly running a crime syndicate.",
                        "programmeurl": "https://d2sqx12cok5m5h.cloudfront.net/PICTURES_Radhe_1191829.jpg",
                        "channelid": "&Pictures",
                        "date": "20240918",
                        "episode-num": "",
                        "sub-title": "",
                        "genre": "Action",
                        "subgenre": "Thriller",
                        "languagename": "Hindi",
                        "isoriginal": "False",
                        "duration": "231",
                        "seasonid": null,
                        "seasonname": null,
                        "rating": "U/A",
                        "country_of_origin": "India",
                        "awards": "",
                        "productionhouse": "Zee Studios, Salman Khan Films, Sohail Khan Productions, Reel Life Production Private Limited",
                        "release_date": "2021",
                        "cast": "Salman Khan, Disha Patani, Randeep Hooda, Jackie Shroff",
                        "crew": "Director: Prabhu Deva; Producer: Salman Khan, Sohail Khan,  Atul Agnihotri, Nikhil Namit; Writer: A.C Mugil, Vijay Maurya"
                      }
                    ]
                  }
                ]
              }
            }
            """;
        String result = getProgramJson(jsonContent, "&Pictures", "333450");
        System.out.println(result);
    }
}
